# creates app gateway for containers resource and association
apiVersion: alb.networking.azure.io/v1
kind: ApplicationLoadBalancer
metadata:
  name: alb-test
  namespace: alb
spec:
  associations:
  - /subscriptions/24ef1668-95f3-4c77-adf2-2d023271a3e1/resourceGroups/MC_rg-aks-agc_agccluster_eastus2/providers/Microsoft.Network/virtualNetworks/aks-vnet-21266979/subnets/agc